### ISSUE TITLE
Need a back-to-top button

### ISSUE THREAD

**Issue by palakg01** [pccoeacm/hacktoberfest#13]

**Comment by palakg01** [comment]
can i work on it?

**Comment by JayeshShelar** [comment]
> can i work on it?

@palakg01 I have assigned you the issue. You can start working on it!

**Comment by tejasmorkar** [comment]
> _No description provided._

Please provide proper descriptions on further issues 😄

**Comment by palakg01** [comment]
Yeah will keep that in mind xD @tejasmorkar
