### ISSUE TITLE
MapValueToRange Function

### ISSUE THREAD

**Issue by pratik-dhende** [pccoeacm/hacktoberfest#14]
This function will take a value within a certain range and map it to the value of other range.
Eg - 
      2 falls in the middle of 1 and 3, but what will be its value if we change the range to 0 and 1, then it will map to 0.5 in this range.
      MapValueToRange(original_value, original_min, original_max, new_min, new_max)
      MapValueToRange(2, 1, 3, 0, 1)       //Returns 0.5 

I would like to work on this.

**Comment by tejasmorkar** [comment]
Please open your issues on particular repos only. 

I suppose you want to contribute to all-calc repo. 😄

**Comment by pratik-dhende** [comment]
Sorry, I got confused with the tabs. I closed the issue now
