### ISSUE TITLE
Footer for  home page and color of header and footer is same

### ISSUE THREAD

**Issue by Dhanno2410** [pccoeacm/hacktoberfest#16]
In the home page there is need of different type of footer and  color of header footer should be same.

**Comment by tejasmorkar** [comment]
Can you please elaborate?

**Comment by Dhanno2410** [comment]
As per standard website , header and footer both have same color. As well as in footer we also add some points

**Comment by tejasmorkar** [comment]
@nupur-shiturkar can you please look into this issue and discuss whether this is required?

**Comment by nupur-shiturkar** [comment]
@Dhanno2410 First of all, I'd like to apologize for replying late. 
It is not really necessary for the header and footer to have the same color. Also, there is no compulsion to have some points in the footer. All this depends upon the requirements, and right now, the website is according to the requirements.
However, I appreciate your will to contribute to this project. You can always look out for some other stuff which will actually help in making the website better.
All the best! Keep up the good work👍
