### ISSUE TITLE
Rearranging Sections

### ISSUE THREAD

**Issue by tejasmorkar** [pccoeacm/hacktoberfest#22]
# Todo

The `Prizes` section should be placed after the `Global stats for Hacktoberfest 2019` section and before the `Associated Repositories` section.

![image](https://user-images.githubusercontent.com/35477326/95115999-fc3dd700-0763-11eb-9408-c0b5619bbac6.png)

---

![image](https://user-images.githubusercontent.com/35477326/95116010-ffd15e00-0763-11eb-871a-2ba268e72bb0.png)

**Comment by SvA1** [comment]
I can do this :)

**Comment by tejasmorkar** [comment]
I'll assign it to you @SvA1
