### ISSUE TITLE
Repository Cards Design on Mobile/Tablets

### ISSUE THREAD

**Issue by anchal-gupta** [pccoeacm/hacktoberfest#24]
Bug - "Associated Repository" Cards on mobile view gets compacted and don't showcase a margin among themselves. However, margin is shown after every 3 cards (whenever there is line-break on desktop). 

Steps to reproduce the behaviour:
1. Go to 'https://pccoeacm.github.io/hacktoberfest/'
2. Make Sure you are viewing website on mobile or have switched to 'mobile view' from desktop.
3. Scroll down to 'Associated Repositories' headline.
4. See Cards arranged below. After every 3 cards, there is margin.

**Expected behaviour**
All cards should have margin among themselves.

**Comment by anchal-gupta** [comment]
![1601973610956](https://user-images.githubusercontent.com/37269403/95180691-f4237d00-07df-11eb-9bf6-4b05f6a4e9ac.JPEG)

**Comment by tejasmorkar** [comment]
Thank you for the catch @anchal-gupta!

Do you want to work on this issue or should I make it open for contributions to others?

**Comment by anchal-gupta** [comment]
I want to contribute to this issue. Please assign it to me @tejasmorkar

**Comment by anchal-gupta** [comment]
I have done the necessary changes on my local, shall I submit my PR Please ?

**Comment by tejasmorkar** [comment]
Yes, sure @anchal-gupta.

Please mention this issue in the PR and provide relevant screenshots, if possible.
