### ISSUE TITLE
Add AOS to the cards of "Schedule for the event".

### ISSUE THREAD

**Issue by rutujanemane** [pccoeacm/hacktoberfest#25]
Animation on Scroll and some UI enhancements(the content in the cards is not properly aligned) can be done to those cards for visual improvement.
In AOS, the schedule cards will be given some animation for eg.(fading) and this animation will be in the order of the timing given in that particular card.

**Comment by tejasmorkar** [comment]
Do you want to work on it?

**Comment by rutujanemane** [comment]
Yes
