### ISSUE TITLE
Linking the logos in navbar to the respective websites.

### ISSUE THREAD

**Issue by sneha-pujari** [pccoeacm/hacktoberfest#31]
The logos of PCCOE ACM and  Hacktoberfest in the navbar can be linked to the sites https://pccoe.acm.org/  and  https://hacktoberfest.digitalocean.com/ respectively.

 I would like to work on this if possible.
 
![Screenshot 2020-10-16 203828](https://user-images.githubusercontent.com/58720128/96275628-949f4b80-0fef-11eb-80d1-ef7da265a014.png)

**Comment by tejasmorkar** [comment]
Great idea 👍  You can start working on it.

**Comment by sneha-pujari** [comment]
I have created a pull request with the required changes. Please could you review it.
Thank you!
